version: "3"
services:
  openq-json-rpc-node:
    image: openq/openq-json-rpc-node:latest
    container_name: ethnode
    hostname: ethnode
    ports:
      - "8545:8545"
  openq-contracts:
    container_name: openq-contracts
    depends_on:
      - openq-json-rpc-node
    build:
      dockerfile: Dockerfile
      context: ./
    volumes:
      - /app/node_modules
      - ./:/app
